import asyncio
import json
import logging
import os
import re
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Annotated, cast

import uvicorn
from fastapi import Depends, FastAPI, File, Form, HTTPException, Request, Response, UploadFile
from fastapi.responses import FileResponse, HTMLResponse
from sqlalchemy.ext.asyncio import AsyncSession

from gigaam_transcriber import GigaAMTranscriber
from gigaam_transcriber.auth import bootstrap_admin, get_current_user
from gigaam_transcriber.rate_limit import ip_rate_limit
from gigaam_transcriber.settings import is_development
from gigaam_transcriber.utils import setup_logging
from gigaam_transcriber.database import async_session_factory
from gigaam_transcriber.models import User

from routers._helpers import (
    _handle_transcription_exception,
    _map_format,
    _result_response,
    _verify_auth,
)
from routers._uploads import (
    BodySizeLimitMiddleware,
    openai_error_detail,
    spool_upload,
    sweep_stale_tempfiles,
)
from routers.correlation import CorrelationIdMiddleware, install_correlation_logging

HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", "7860"))


def is_development_mode() -> bool:
    return is_development()


_DOCS_ENABLED = is_development_mode()

logger = logging.getLogger("dialogscribe-api")

# SvelteKit SPA build directory
_BUILD_DIR = Path(__file__).parent / "frontend" / "build"


@asynccontextmanager
async def lifespan(app: FastAPI):
    setup_logging()
    install_correlation_logging()
    transcriber = GigaAMTranscriber()
    app.state.transcriber = transcriber
    logger.info("DialogScribe API starting — transcriber initialized")

    swept = await asyncio.to_thread(sweep_stale_tempfiles)
    if swept:
        logger.info("Startup sweep removed %d stale upload temp files", swept)

    # Bootstrap admin user from ADMIN_EMAIL / ADMIN_PASSWORD env vars
    async with async_session_factory() as db:
        try:
            await bootstrap_admin(db)
        except Exception:
            logger.exception("Failed to bootstrap admin user")

    yield
    transcriber.cleanup()
    logger.info("DialogScribe API shutting down — transcriber cleaned up")


app = FastAPI(
    title="DialogScribe API",
    lifespan=lifespan,
    docs_url="/docs" if _DOCS_ENABLED else None,
    redoc_url="/redoc" if _DOCS_ENABLED else None,
    openapi_url="/openapi.json" if _DOCS_ENABLED else None,
)

# Registered before the security-headers decorator so the raw-body 413
# responses still flow outward through it (and keep CSP headers).
app.add_middleware(BodySizeLimitMiddleware)
app.add_middleware(CorrelationIdMiddleware)
install_correlation_logging()

# Defense-in-depth browser hardening for every response (SPA included):
# scripts/styles/images/media only from same origin (plus blob: media for
# upload audio previews), no plugins/frames, and no content-type sniffing.
# WebSocket upgrades are allowed for the live APIs.
# SvelteKit pages embed inline bootstrap scripts (theme init + `__sveltekit_*`
# config), so script-src additionally allows their build-time sha256 hashes
# from frontend/build/csp-hashes.json (generated by the frontend postbuild).
_CSP_TEMPLATE = (
    "default-src 'self'; "
    "script-src {script_sources}; "
    "style-src 'self' 'unsafe-inline'; "
    "img-src 'self' data:; "
    "media-src 'self' blob:; "
    "connect-src 'self' ws: wss:; "
    "object-src 'none'; "
    "frame-ancestors 'none'; "
    "base-uri 'self'"
)

_CSP_HASHES_FILENAME = "csp-hashes.json"
_CSP_HASH_PATTERN = re.compile(r"^sha256-[A-Za-z0-9+/=]{44}$")
_csp_cache: tuple[int, str] | None = None


def _script_src_directive() -> str:
    global _csp_cache

    hashes_path = _BUILD_DIR / _CSP_HASHES_FILENAME
    try:
        mtime_ns = hashes_path.stat().st_mtime_ns
        entries = json.loads(hashes_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        entries = None
        mtime_ns = None

    if isinstance(entries, list):
        hashes = sorted(
            {entry for entry in entries if isinstance(entry, str) and _CSP_HASH_PATTERN.match(entry)}
        )
    else:
        hashes = []

    if hashes:
        if _csp_cache is None or _csp_cache[0] != mtime_ns:
            script_sources = " ".join(["'self'", *(f"'{entry}'" for entry in hashes)])
            _csp_cache = (mtime_ns, _CSP_TEMPLATE.format(script_sources=script_sources))
        return _csp_cache[1]

    if is_development_mode():
        logger.warning(
            "%s not found or invalid under %s; script-src falls back to "
            "'self' 'unsafe-inline' (development only — rebuild the frontend "
            "to regenerate hashes)",
            _CSP_HASHES_FILENAME,
            _BUILD_DIR,
        )
        return _CSP_TEMPLATE.format(script_sources="'self' 'unsafe-inline'")

    return _CSP_TEMPLATE.format(script_sources="'self'")


@app.middleware("http")
async def security_headers_middleware(request: Request, call_next):
    response = await call_next(request)
    response.headers["Content-Security-Policy"] = _script_src_directive()
    response.headers["X-Content-Type-Options"] = "nosniff"
    return response


@app.get("/health")
def health():
    return {"status": "healthy", "transcriber": "ready"}


@app.post("/v1/audio/transcriptions")
def create_transcription(
    file: Annotated[UploadFile, File()],
    auth: Annotated[None, Depends(_verify_auth)],
    _rate_limit: Annotated[None, Depends(ip_rate_limit("v1_transcription"))],
    model: Annotated[str, Form()] = "whisper-1",
    language: Annotated[str | None, Form()] = None,
    response_format: Annotated[str, Form()] = "json",
) -> Response:
    _ = model, auth
    try:
        with spool_upload(file, error_detail=openai_error_detail) as tmp_path:
            transcriber = cast(GigaAMTranscriber, app.state.transcriber)
            result = transcriber.transcribe(
                input_path=tmp_path,
                diarization="none",
                language=language or "ru",
                output_format=_map_format(response_format),
            )
            return _result_response(result, response_format)
    except HTTPException:
        raise
    except Exception as e:
        raise _handle_transcription_exception(e)


from routers import admin, analysis, autoflow, exports, live_hints, meeting_prep, saved_transcriptions, settings, templates, transcription, usage  # noqa: E402
from routers.auth import auth_router  # noqa: E402

app.include_router(auth_router)
app.include_router(transcription.router)
app.include_router(analysis.router)
app.include_router(templates.router)
app.include_router(exports.router)
app.include_router(autoflow.router)
app.include_router(usage.router)
app.include_router(admin.router)
app.include_router(saved_transcriptions.router)
app.include_router(live_hints.router)
app.include_router(meeting_prep.router)
app.include_router(settings.router)


_MINDMAP_RETIRED_DETAIL = '{"detail":"Mindmap HTML endpoints are retired"}'


@app.get("/mindmap/{uid}", status_code=410)
async def mindmap_tombstone(uid: str) -> Response:
    """Static 410 tombstone for the retired executable mindmap HTML routes.

    Registered before the SPA catch-all so client-side-routing fallback can
    never convert this into an HTML response. Mindmaps remain available as
    Markdown via POST /api/mindmap.
    """
    _ = uid
    return Response(status_code=410, content=_MINDMAP_RETIRED_DETAIL, media_type="application/json")


# Serve SvelteKit SPA — catch-all route for client-side routing.
# Registered last so explicit API routes (including the 410 tombstone above)
# always take precedence.
_SPA_INDEX = _BUILD_DIR / "index.html"


@app.get("/{path:path}")
async def spa_fallback(path: str):
    """Serve SPA static assets or fall back to index.html for client-side routing.

    The resolved path must stay inside the frontend build directory; any
    request that resolves outside it (traversal, absolute paths) is a 404.
    """
    build_dir = _BUILD_DIR.resolve()
    try:
        resolved = (build_dir / path).resolve()
        resolved.relative_to(build_dir)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail="Not Found") from exc
    if path and resolved.is_file():
        return FileResponse(resolved)
    if _SPA_INDEX.is_file():
        return HTMLResponse(content=_SPA_INDEX.read_text())
    raise HTTPException(status_code=404, detail="Not Found")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    uvicorn.run(app, host=HOST, port=PORT, timeout_keep_alive=300)
