"""Hint typology models for the Live Advisor Agent."""

import enum
import uuid
from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field


class HintType(str, enum.Enum):
    """Type of hint — determines semantics and UI presentation."""
    TACTICAL = "tactical"      # Immediate action: "ask about budget now"
    STRATEGIC = "strategic"    # Directional: "shift focus to delivery terms"
    WARNING = "warning"        # Alert: "client mentioned competitor X"
    ANALYTICAL = "analytical"  # Background: "discussion shifted from price to timeline"


class HintPriority(str, enum.Enum):
    """Priority level — determines display ordering and urgency."""
    CRITICAL = "critical"  # Immediate attention needed
    HIGH = "high"          # Important, show prominently
    MEDIUM = "medium"      # Useful, standard display
    LOW = "low"            # Background information


# Priority ordering for sorting (higher index = higher priority)
_PRIORITY_ORDER = {
    HintPriority.LOW: 0,
    HintPriority.MEDIUM: 1,
    HintPriority.HIGH: 2,
    HintPriority.CRITICAL: 3,
}


class Hint(BaseModel):
    """Structured hint generated by the Live Advisor Agent."""
    hint_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    type: HintType = HintType.TACTICAL
    text: str
    priority: HintPriority = HintPriority.MEDIUM
    rationale: str = ""
    timestamp: float = Field(default_factory=lambda: datetime.now(timezone.utc).timestamp())

    def priority_order(self) -> int:
        """Return numeric priority for sorting (higher = more urgent)."""
        return _PRIORITY_ORDER.get(self.priority, 0)
